/**
 * Basic Node Definitions for Initial FlowForge AI MVP
 */

export const STARTER_NODES = {
  input: {
    type: 'input',
    label: 'Input Node',
    category: 'Inputs',
    description: 'Receives input text or prompt query.',
    color: '#3b82f6',
    inputs: [],
    outputs: ['query'],
    defaultParams: { query: '' },
  },
  prompt: {
    type: 'prompt',
    label: 'Prompt Template',
    category: 'AI',
    description: 'Formats query into a structured prompt.',
    color: '#10b981',
    inputs: ['query'],
    outputs: ['prompt'],
    defaultParams: { template: 'User question: {query}' },
  },
  promptTemplate: {
    type: 'promptTemplate',
    label: 'Prompt Template (Context)',
    category: 'AI',
    description: 'Formats context and question into a structured prompt template.',
    color: '#10b981',
    inputs: ['context'],
    outputs: ['prompt'],
    defaultParams: {
      template: 'Context:\n{{input}}\n\nQuestion:\n{{question}}\n\nPlease answer the question based on the provided context.',
    },
  },
  llm: {
    type: 'llm',
    label: 'LLM Node',
    category: 'AI',
    description: 'Calls language model to generate response.',
    color: '#6366f1',
    inputs: ['prompt'],
    outputs: ['response'],
    defaultParams: { provider: 'gemini', model: 'gemini-flash-lite-latest', temperature: 0.7, max_tokens: 2048 },
    modelOptions: {
      gemini: ['gemini-flash-lite-latest', 'gemini-3.1-flash-lite', 'gemini-flash-latest'],
    },
  },
  output: {
    type: 'output',
    label: 'Output Node',
    category: 'Outputs',
    description: 'Displays the final generated response.',
    color: '#f59e0b',
    inputs: ['response'],
    outputs: [],
    defaultParams: {},
  },
  documentLoader: {
    type: 'documentLoader',
    label: 'Document Loader',
    category: 'RAG',
    description: 'Loads a document for RAG processing.',
    color: '#8b5cf6',
    inputs: [],
    outputs: ['document'],
    defaultParams: { filePath: '' },
  },
  textSplitter: {
    type: 'textSplitter',
    label: 'Text Splitter',
    category: 'RAG',
    description: 'Splits documents into smaller chunks.',
    color: '#8b5cf6',
    inputs: ['document'],
    outputs: ['chunks'],
    defaultParams: { chunk_size: 1000, chunk_overlap: 200 },
  },
  embedding: {
    type: 'embedding',
    label: 'Embedding Engine',
    category: 'RAG',
    description: 'Generates embeddings from text chunks.',
    color: '#8b5cf6',
    inputs: ['chunks'],
    outputs: ['embeddings'],
    defaultParams: { provider: 'gemini', model: 'models/text-embedding-004' },
  },
  vectorDb: {
    type: 'vectorDb',
    label: 'Vector DB (Qdrant)',
    category: 'RAG',
    description: 'Stores embeddings in a vector database.',
    color: '#ec4899',
    inputs: ['embeddings'],
    outputs: ['collection'],
    defaultParams: { collection_name: 'default_collection' },
  },
  retriever: {
    type: 'retriever',
    label: 'Retriever Node',
    category: 'RAG',
    description: 'Retrieves relevant context based on query.',
    color: '#ec4899',
    inputs: ['collection', 'query'],
    outputs: ['context'],
    defaultParams: { top_k: 4 },
  },
};
